"""
Ghidra headless script: Re-export the full decompiled C file.

Iterates every function in the program, runs the decompiler, and writes
the result to research/smartpid_decompiled_v2.c.

Run AFTER 01_import_rom_symbols.py and 02_define_config_struct.py so the
output benefits from resolved ROM names and typed struct fields.

This will take 20–60 minutes for a 350K-line binary.  Progress is printed
every 500 functions.

Run via analyzeHeadless — see run_pipeline.sh.
"""

import os
from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "smartpid_decompiled_v2.c"
)

DECOMPILE_TIMEOUT_S = 60   # per-function timeout
REPORT_EVERY        = 500  # print progress every N functions

# ── Set up decompiler ─────────────────────────────────────────────────────────
ifc = DecompInterface()
opts = DecompileOptions()
ifc.setOptions(opts)
ifc.openProgram(currentProgram)

monitor  = ConsoleTaskMonitor()
func_mgr = currentProgram.getFunctionManager()
funcs    = list(func_mgr.getFunctions(True))   # True = forward order
total    = len(funcs)

print("[03] {} functions to decompile → {}".format(total, OUT_PATH))

succeeded = 0
failed    = 0
skipped   = 0

with open(OUT_PATH, "w") as f:
    f.write("// SmartPID M5 PRO — re-exported decompile\n")
    f.write("// Program : {}\n".format(currentProgram.getName()))
    f.write("// Passes  : ROM symbols imported, g_config struct applied\n")
    f.write("// Generated by research/scripts/03_export_decompiled.py\n")
    f.write("//\n")
    f.write("// Post-processed by 04_postprocess.sh:\n")
    f.write("//   undefined4  → uint32_t\n")
    f.write("//   undefined2  → uint16_t\n")
    f.write("//   undefined1  → uint8_t\n")
    f.write("//   (float)(int)x / 1.0  → (float)x\n")
    f.write("\n")

    for i, func in enumerate(funcs):
        if i % REPORT_EVERY == 0:
            print("[03] {}/{} ({:.0f}%)  last: {}".format(
                i, total, 100.0 * i / total, func.getName()))

        # Skip external/thunk stubs — they add noise without content
        if func.isExternal() or func.isThunk():
            skipped += 1
            continue

        try:
            result = ifc.decompileFunction(func, DECOMPILE_TIMEOUT_S, monitor)
        except Exception as e:
            f.write("/* ERROR decompiling {} : {} */\n\n".format(func.getName(), e))
            failed += 1
            continue

        if result is None or not result.decompileCompleted():
            err = result.getErrorMessage() if result else "timeout/null"
            f.write("/* FAILED {} : {} */\n\n".format(func.getName(), err))
            failed += 1
            continue

        decomp = result.getDecompiledFunction()
        if decomp is None:
            skipped += 1
            continue

        c_code = decomp.getC()
        if c_code:
            f.write(c_code)
            f.write("\n\n")
            succeeded += 1
        else:
            skipped += 1

ifc.dispose()
print("[03] Done.  succeeded={} failed={} skipped={}".format(
    succeeded, failed, skipped))
print("[03] Output: {}".format(OUT_PATH))
